import { type NextPage } from "next";
import Head from "next/head";
import { Tab } from "@headlessui/react";

import { api } from "../utils/api";
import { Tabs } from "../components/Tabs";
import { SpendForm } from "../components/SpendForm";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-gradient-to-b from-black to-gray-900">
        <Tab.Group defaultIndex={1}>
          <Tab.Panels className="container flex flex-col items-center">
            <Tab.Panel className="text-white">Tab 1 content</Tab.Panel>
            <Tab.Panel>
              <div>
                <h1 className="mt-8 text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
                  Income <span className="text-[hsl(280,100%,70%)]">Dist</span>
                </h1>

                <p className="mt-4 text-lg text-gray-300">
                  {hello.data?.greeting ?? "Loading..."}
                </p>

                <SpendForm />
              </div>
            </Tab.Panel>
            <Tab.Panel className="text-white">Tab 3 content</Tab.Panel>
          </Tab.Panels>
          <Tabs tabs={["History", "Home", "Settings"]} />
        </Tab.Group>
      </main>
    </>
  );
};

export default Home;
