import { type NextPage } from "next";
import Head from "next/head";
import { Tab } from "@headlessui/react";

import { api } from "../utils/api";
import { Tabs } from "../components/Tabs";
import { SpendForm } from "../components/SpendForm";
import { map } from "lodash";
import { useSession } from "next-auth/react";
import { Login } from "../components/Login";

const HomeContent = () => {
  const { data: recentSpends, isLoading, error } = api.spend.getAll.useQuery();
  return (
    <>
      <p className="mt-4 text-lg text-gray-300">
        {error
          ? "error"
          : isLoading
          ? "Loading..."
          : map(recentSpends, "amount")}
      </p>
      <SpendForm />
    </>
  );
};

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  console.log(sessionData);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-gradient-to-b from-black to-gray-900 ">
        <Tab.Group defaultIndex={1}>
          <Tab.Panels className="container flex flex-1 flex-col items-center p-8">
            <Tab.Panel className="text-white">Tab 1 content</Tab.Panel>
            <Tab.Panel className="flex flex-1 flex-col">
              <h1 className="text-5xl font-extrabold tracking-tight text-white">
                Income <span className="text-fuchsia-500">Dist</span>
              </h1>

              {!sessionData ? <Login /> : <HomeContent />}
            </Tab.Panel>
            <Tab.Panel className="text-white">Tab 3 content</Tab.Panel>
          </Tab.Panels>
          <Tabs tabs={["History", "Home", "Settings"]} />
        </Tab.Group>
      </main>
    </>
  );
};

export default Home;
